# Generated by Django 6.1.1 on 2026-09-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_alter_batch_batch_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_medicine_batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier_batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_batch_number__gt', '')), fields=('medicine', 'supplier_batch_number'), name='unique_medicine_batch'),
        ),
    ]
