# Generated by Django 6.1.1 on 2026-09-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique_supplier_invoice',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
